name: Login

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Temporary GitHub code from App authorization'
        required: true

jobs:
  login:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.login-script.outputs.result }}
    steps:
      - name: Login
        uses: actions/github-script@v6
        id: login-script
        env:
          code: ${{ inputs.code }}
        with:
          result-encoding: string
          script: |
            const { code } = process.env;
            const response = await fetch("https://api.github.com/api/github/oauth/token", {
              method: "POST",
              headers: {
                "content-type": "application/json",
              },
              body: JSON.stringify({ code }),
            });
            const { token } = await response.json();
            return token;
      - name: Result
        run: echo ${{ steps.login-script.outputs.result }}